import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {normalizeTicker,validateMaster,selectedSymbol,searchSymbols,registerWatch,loadSymbols,fromForm,manyFromForm,verifyIncoming} from '../assets/js/symbols.js';
import {fresh,validate} from '../assets/js/state.js';
const raw=JSON.parse(fs.readFileSync(new URL('../data/symbols.json',import.meta.url)));const rows=validateMaster(raw),nvda=rows.find(r=>r.symbol==='NVDA'&&r.exchange==='NASDAQ');
test('NVDA and whitespace/lowercase normalize; NVD offers company and market, but selection is required',()=>{for(const value of ['NVDA','nvda',' NVDA ']){assert.equal(normalizeTicker(value),'NVDA');assert.equal(selectedSymbol(rows,value,nvda.id).symbol,'NVDA');}assert.ok(searchSymbols(rows,'NVD').some(r=>r.id===nvda.id&&r.name==='NVIDIA Corporation'));assert.throws(()=>selectedSymbol(rows,'NVDA',''));assert.throws(()=>selectedSymbol(rows,'NVDAAAA',nvda.id));assert.equal(searchSymbols(rows,'NVDAAAA').length,0);});
test('duplicate watch ticker cannot be saved twice; non-theme AAPL can be registered',()=>{const s=fresh();registerWatch(s,nvda);assert.throws(()=>registerWatch(s,nvda),/登録済み/);assert.equal(s.watch.filter(x=>x==='NVDA').length,1);const a=rows.find(x=>x.symbol==='AAPL'&&x.exchange==='NASDAQ');assert.ok(!fs.readFileSync(new URL('../config/entities.csv',import.meta.url),'utf8').includes(',AAPL,'));registerWatch(s,a);assert.ok(s.watch.includes('AAPL'));assert.equal(s.securities.AAPL.exchange,'NASDAQ');validate(s);});
test('same symbol in different markets requires the selected listing ID',()=>{const other={...nvda,id:'NVDA|TEST',exchange:'TEST'};assert.equal(selectedSymbol([nvda,other],'nvda',other.id).exchange,'TEST');assert.throws(()=>selectedSymbol([nvda,other],'NVDA',''));});
test('shared form validation covers holdings, dividends and multiple news tickers; failed master closes registration',async()=>{globalThis.fetch=async()=>({ok:true,json:async()=>raw});await loadSymbols();const f=new FormData();f.set('ticker',' nvda ');f.set('ticker_id',nvda.id);assert.equal(fromForm(f).symbol,'NVDA');f.set('tickers',JSON.stringify([nvda.id,nvda.id]));assert.equal(manyFromForm(f).length,1);const next=fresh();next.watch.push('NVDAAAA');assert.throws(()=>verifyIncoming(next,fresh()));globalThis.fetch=async()=>({ok:false,status:429});await loadSymbols();assert.throws(()=>fromForm(f));});
test('manifest is subpath-safe and standalone, and actual PNG sizes match declarations',()=>{const manifest=JSON.parse(fs.readFileSync(new URL('../manifest.webmanifest',import.meta.url)));assert.equal(manifest.display,'standalone');assert.equal(manifest.name,'株ゴリラ🦍');assert.equal(manifest.scope,'./');assert.equal(manifest.start_url,'./#home');for(const [file,size] of [['apple-touch-icon.png',180],['icon-192.png',192],['icon-512.png',512]]){const b=fs.readFileSync(new URL('../assets/icons/'+file,import.meta.url));assert.equal(b.readUInt32BE(16),size);assert.equal(b.readUInt32BE(20),size);}const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.match(html,/apple-mobile-web-app-capable/);assert.match(html,/apple-mobile-web-app-title/);assert.match(html,/viewport-fit=cover/);assert.ok(!fs.readFileSync(new URL('../assets/js/symbols.js',import.meta.url),'utf8').includes('api.twelvedata.com'));});
